### ISSUE TITLE
Problems to execute

### ISSUE THREAD

**Issue by lievertonh** [dancsalo/TensorFlow-MIL#2]
Hi, i was trying yo run your code, we found few errors with new version of tensorflow-gpu, but we solved those problems, and now, the code run, but he just end after run just once, how to make it train network properly, and use the model?

Thanks for your time.

**Comment by dancsalo** [comment]
Hi Lieverton,

Thanks for your interest in this code base. We made some updates to
TensorBase last week, and I have not yet had time to work changes in the
MIL model. I will work on it over the weekend and let you know.

Thanks,

Dan

**Comment by dancsalo** [comment]
@Lieverton the model is working properly now with the simple MNIST example. Let me know if you have any further issues.

**Comment by lievertonh** [comment]
@dancsalo Thanks a lot!  the new version will be really helpful.
