### ISSUE TITLE
The additional fully connected layer and the joint cross entropy objective function make me confused.

### ISSUE THREAD

**Issue by Andysis** [dancsalo/TensorFlow-MIL#3]
It seems that the additional fully connected layer and the joint cross entropy objective function were not implemented in these codes. Do you have any idea how to implement them? Parts about these two in the original paper make me pretty confused.

**Comment by dancsalo** [comment]
Hi @Andysis, I updated the code with the additional fully connected layer and the joint cross entropy objective function. I also provided a brief explanation in the README. I hope that helps.
